apiVersion: v1
kind: Service
metadata:
  name: random-service
  labels:
    run: random
    app: random-server
    tier: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: random
    app: random-server
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: randint-service
  labels:
    run: randint
    app: randint-server
    tier: backend
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    run: randint
    app: randint-server
    tier: backend
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: random
  labels:
    run: random
    app: random-server
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: random
      app: random-server
      tier: backend
  template:
    metadata:
      labels:
        run: random
        app: random-server
        tier: backend
    spec:
      containers:
        - name: random-server
          image: fuzzyfrog/random-server:v1
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: randint
  labels:
    run: randint
    app: randint-server
    tier: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      run: randint
      app: randint-server
      tier: backend
  template:
    metadata:
      labels:
        run: randint
        app: randint-server
        tier: backend
    spec:
      containers:
        - name: randint-server
          image: fuzzyfrog/randint-server:v2
          ports:
            - containerPort: 8081
